/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as DashboardLayoutImport } from './routes/_dashboardLayout'
import { Route as DashboardLayoutIndexImport } from './routes/_dashboardLayout/index'
import { Route as DashboardLayoutAboutImport } from './routes/_dashboardLayout/about'

// Create/Update Routes

const DashboardLayoutRoute = DashboardLayoutImport.update({
  id: '/_dashboardLayout',
  getParentRoute: () => rootRoute,
} as any)

const DashboardLayoutIndexRoute = DashboardLayoutIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardLayoutRoute,
} as any)

const DashboardLayoutAboutRoute = DashboardLayoutAboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => DashboardLayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_dashboardLayout': {
      id: '/_dashboardLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DashboardLayoutImport
      parentRoute: typeof rootRoute
    }
    '/_dashboardLayout/about': {
      id: '/_dashboardLayout/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof DashboardLayoutAboutImport
      parentRoute: typeof DashboardLayoutImport
    }
    '/_dashboardLayout/': {
      id: '/_dashboardLayout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardLayoutIndexImport
      parentRoute: typeof DashboardLayoutImport
    }
  }
}

// Create and export the route tree

interface DashboardLayoutRouteChildren {
  DashboardLayoutAboutRoute: typeof DashboardLayoutAboutRoute
  DashboardLayoutIndexRoute: typeof DashboardLayoutIndexRoute
}

const DashboardLayoutRouteChildren: DashboardLayoutRouteChildren = {
  DashboardLayoutAboutRoute: DashboardLayoutAboutRoute,
  DashboardLayoutIndexRoute: DashboardLayoutIndexRoute,
}

const DashboardLayoutRouteWithChildren = DashboardLayoutRoute._addFileChildren(
  DashboardLayoutRouteChildren,
)

export interface FileRoutesByFullPath {
  '': typeof DashboardLayoutRouteWithChildren
  '/about': typeof DashboardLayoutAboutRoute
  '/': typeof DashboardLayoutIndexRoute
}

export interface FileRoutesByTo {
  '/about': typeof DashboardLayoutAboutRoute
  '/': typeof DashboardLayoutIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_dashboardLayout': typeof DashboardLayoutRouteWithChildren
  '/_dashboardLayout/about': typeof DashboardLayoutAboutRoute
  '/_dashboardLayout/': typeof DashboardLayoutIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '' | '/about' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/about' | '/'
  id:
    | '__root__'
    | '/_dashboardLayout'
    | '/_dashboardLayout/about'
    | '/_dashboardLayout/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  DashboardLayoutRoute: typeof DashboardLayoutRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  DashboardLayoutRoute: DashboardLayoutRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_dashboardLayout"
      ]
    },
    "/_dashboardLayout": {
      "filePath": "_dashboardLayout.tsx",
      "children": [
        "/_dashboardLayout/about",
        "/_dashboardLayout/"
      ]
    },
    "/_dashboardLayout/about": {
      "filePath": "_dashboardLayout/about.tsx",
      "parent": "/_dashboardLayout"
    },
    "/_dashboardLayout/": {
      "filePath": "_dashboardLayout/index.tsx",
      "parent": "/_dashboardLayout"
    }
  }
}
ROUTE_MANIFEST_END */
