services:
  postgres:
    image: postgres:17-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shopz
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data

  kafka:
    image: confluentinc/cp-kafka
    restart: always
    ports:
      - 9092:9092
    environment:
      KAFKA_ZOOKEEPER_CONNECT: localhost:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

    depends_on:
      - zookeeper
    volumes:
      - ./data/kafka:/var/lib/kafka/data

  zookeeper:
    image: confluentinc/cp-zookeeper
    restart: always
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

volumes:
  postgres:
  redis:
  taskhive:
  inventoryz:
