import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@repo/ui/styles.css";
import NextTopLoader from "nextjs-toploader";
import ApiClientProvider from "../components/api-client-provider";

const font = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "ShopZ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${font.className} antialiased`}>
        <NextTopLoader />
        <ApiClientProvider>{children}</ApiClientProvider>
      </body>
    </html>
  );
}
